package com.bkarakoca.fooddeliveryapp.domain.restaurant

import com.bkarakoca.fooddeliveryapp.R
import com.bkarakoca.fooddeliveryapp.data.uimodel.restaurant.*
import com.bkarakoca.fooddeliveryapp.data.uimodel.restaurant.listitem.RestaurantHeaderUIModel
import com.bkarakoca.fooddeliveryapp.data.uimodel.restaurant.listitem.RestaurantListItemType
import com.bkarakoca.fooddeliveryapp.data.uimodel.restaurant.listitem.RestaurantUIModel

class GetRestaurantListUseCaseDataProvider {

    fun getRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true,
            ),
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true,
            )
        )
    }

    fun getClosedRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = false,
            ),
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = false,
            )
        )
    }

    fun getClosedFavoriteRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true,
            ),
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true,
            )
        )
    }

    fun getOpenFavoriteRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true,
            ),
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true,
            )
        )
    }

    fun getClosingRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.ORDER_AHEAD,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = false,
            ),
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.ORDER_AHEAD,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = false
            ),
        )
    }

    fun getClosingFavoriteRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.ORDER_AHEAD,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true,
            ),
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.ORDER_AHEAD,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true
            ),
        )
    }


    fun getNotFavoriteSortedRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = false,
            ),
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = false
            ),
        )
    }

    fun getSortedRestaurantList(): List<RestaurantUIModel> {
        return listOf(
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true,
            ),
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true
            ),
        )
    }

    fun getSectionedRestaurantList(): RestaurantListUIModel {
        return RestaurantListUIModel(
            restaurantItemList = listOf(
                RestaurantHeaderUIModel(
                    id = 0L,
                    layoutId = -1,
                    header = "asd",
                    sectionItemSize = 3
                ),
                RestaurantUIModel(
                    id = 1L,
                    layoutId = -1,
                    restaurantImageResId = R.drawable.restaurant_image,
                    restaurantRatingColorId = R.color.restaurant_black_color,
                    restaurantName = "restaurant",
                    restaurantStatusType = RestaurantStatusType.OPEN,
                    bestMatchText = "1.0",
                    bestMatchValue = 1.0,
                    newestText = "1.0",
                    newestValue = 1.0,
                    restaurantRatingText = "1.0",
                    restaurantRatingValue = 1.0,
                    restaurantDeliveryDurationText = "15-20 min",
                    restaurantDeliveryDurationValue = 30,
                    restaurantPopularityText = "1.0",
                    restaurantPopularityValue = 1.0,
                    averageProductPriceText = "10",
                    averageProductPriceValue = 10,
                    deliveryCostText = "1.5",
                    deliveryCostValue = 1.5,
                    minimumCostText = "3.5",
                    minimumCostValue = 3.5,
                    isRestaurantFavorite = true,
                ),
                RestaurantUIModel(
                    2L,
                    -1,
                    R.drawable.restaurant_image,
                    R.color.restaurant_black_color,
                    "restaurant",
                    RestaurantStatusType.OPEN,
                    bestMatchText = "2.0",
                    bestMatchValue = 2.0,
                    newestText = "2.0",
                    newestValue = 2.0,
                    restaurantRatingText = "2.0",
                    restaurantRatingValue = 2.0,
                    restaurantDeliveryDurationText = "15-20 min",
                    restaurantDeliveryDurationValue = 50,
                    restaurantPopularityText = "2.0",
                    restaurantPopularityValue = 2.0,
                    averageProductPriceText = "20",
                    averageProductPriceValue = 20,
                    deliveryCostText = "2.5",
                    deliveryCostValue = 2.5,
                    minimumCostText = "5.5",
                    minimumCostValue = 5.5,
                    isRestaurantFavorite = false,
                ),
            ),
            favoriteRestaurantsItemList = listOf(),
            openRestaurantsItemList = listOf(),
            closingRestaurantsItemList = listOf(),
            closedRestaurantsItemList = listOf()
        )
    }

    fun getRestaurantFavoriteItemList(): List<RestaurantListItemType> {
        return listOf(
            RestaurantHeaderUIModel(
                id = 0L,
                layoutId = -1,
                header = "asd",
                sectionItemSize = 3
            ),
            RestaurantUIModel(
                id = 2L,
                layoutId = -2,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant2",
                restaurantStatusType = RestaurantStatusType.OPEN,
                bestMatchText = "2.0",
                bestMatchValue = 2.0,
                newestText = "2.0",
                newestValue = 2.0,
                restaurantRatingText = "2.0",
                restaurantRatingValue = 2.0,
                restaurantDeliveryDurationText = "35-50 min",
                restaurantDeliveryDurationValue = 50,
                restaurantPopularityText = "2.0",
                restaurantPopularityValue = 2.0,
                averageProductPriceText = "20",
                averageProductPriceValue = 20,
                deliveryCostText = "2.5",
                deliveryCostValue = 2.5,
                minimumCostText = "5.5",
                minimumCostValue = 5.5,
                isRestaurantFavorite = true
            ),
            RestaurantUIModel(
                id = 1L,
                layoutId = -1,
                restaurantImageResId = R.drawable.restaurant_image,
                restaurantRatingColorId = R.color.restaurant_black_color,
                restaurantName = "restaurant",
                restaurantStatusType = RestaurantStatusType.CLOSED,
                bestMatchText = "1.0",
                bestMatchValue = 1.0,
                newestText = "1.0",
                newestValue = 1.0,
                restaurantRatingText = "1.0",
                restaurantRatingValue = 1.0,
                restaurantDeliveryDurationText = "15-20 min",
                restaurantDeliveryDurationValue = 30,
                restaurantPopularityText = "1.0",
                restaurantPopularityValue = 1.0,
                averageProductPriceText = "10",
                averageProductPriceValue = 10,
                deliveryCostText = "1.5",
                deliveryCostValue = 1.5,
                minimumCostText = "3.5",
                minimumCostValue = 3.5,
                isRestaurantFavorite = true
            ),
        )
    }

}